const BASE_SPACING: number = 16;
const DOUBLE_BASE_SPACING: number = BASE_SPACING * 2;
const HALF_BASE_SPACING: number = BASE_SPACING / 2;
const QUARTER_BASE_SPACING: number = BASE_SPACING / 4;
const BASE_AND_HALF_SPACING: number = BASE_SPACING * 1.5;

export const spacing = {
  BASE_SPACING,
  DOUBLE_BASE_SPACING,
  HALF_BASE_SPACING,
  QUARTER_BASE_SPACING,
  BASE_AND_HALF_SPACING,
};
